variables:
  ADVERTISED_HOST: spotify-kafka
  ADVERTISED_PORT: "9092"
  KAFKA_HOST: spotify-kafka
  KAFKA_PORT: "9092"
  KAFKA_TOPIC: cs
  CS_HOST: bwsw-cs-simulator-kafka
  CS_PORT: 8888

stages:
  - test
  - it
  - mirror

test:
  image: hseeberger/scala-sbt:8u151-2.12.4-1.0.4
  stage: test
  script:
    - sbt scalastyle test:scalastyle
    - sbt clean coverage test coverageReport
  coverage: '/Coverage was \[\d+.\d+\%\]/'
  tags:
    - build-in-docker
    - cs-eco-builder

it:
  image: hseeberger/scala-sbt:8u151-2.12.4-1.0.4
  stage: it
  services:
    - spotify/kafka
    - bwsw/cs-simulator-kafka:4.10.3-NP
  script:
    - chmod +x ./wait-cs-simulator.sh && ./wait-cs-simulator.sh
    - sbt scalastyle it:scalastyle
    - sbt clean it:test
  tags:
    - build-in-docker
    - cs-eco-builder

mirror-master:
  image: maven:3.5.4
  stage: mirror
  variables:
    UPSTREAM_REPOSITORY: "git@github.com:bwsw/cs-entities.git"
    UPSTREAM_BRANCH: "master"
    GIT_STRATEGY: clone
  only:
    - master
  script:
    - mkdir -p ~/.ssh
    - echo $GITHUB_MIRROR_PRIVATE | base64 -d > ~/.ssh/id_rsa
    - echo $GITHUB_MIRROR_PUBLIC > ~/.ssh/id_rsa.pub
    - ssh-keyscan -t rsa,dsa,ecdsa github.com >> ~/.ssh/known_hosts
    - chmod -R go-rwx ~/.ssh
    - git remote add mirror $UPSTREAM_REPOSITORY
    - git remote show mirror
    - git fetch mirror
    - git push --progress mirror HEAD:$UPSTREAM_BRANCH
  tags:
    - build-in-docker
    - cs-eco-builder
